/**
 * The runtime pack pipeline (RUNTIMES.md M2). Build-time extraction of upstream
 * runtime assets, pinned and verified the way staticify.mjs vendors Eruda:
 *
 *   node scripts/packs.mjs --list            what is defined and what is pinned
 *   node scripts/packs.mjs --pin <id>...     fetch each asset, record sha256 + bytes in packs/<id>/pack.json
 *   node scripts/packs.mjs --build           verify + emit dist/packs/<id>/ and dist/packs/catalog.json
 *   node scripts/packs.mjs --build --id <id>  build one pack
 *   node scripts/packs.mjs --build --offline  fail instead of fetching (tests, CI)
 *
 * The pipeline never ships an unpinned pack. `--pin` records digests so that a
 * human adding a new version only has to point the URLs and let the tool fill
 * the rest; `--build` then refuses to emit anything whose digest does not
 * match, and it never touches the network unless a file is not already cached.
 *
 * Downloads are cached under .serve/packs-cache/ keyed by sha256, so `--build`
 * is offline once `--pin` has run. That is what makes the endpoint and license
 * gates fast enough to be worth running on every build.
 */
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import {
  catalogEntry,
  installBytesFor,
  isPinned,
  packManifest,
  packPackageJson,
  PACKS_SRC,
  readPackDefinition,
  sha256Hex,
  validatePack,
} from "./packs-lib.mjs";
import { DIST, RC_ROOT } from "./lib.mjs";

/** Where downloaded bytes are cached so --build can run offline. */
export const CACHE_DIR = path.join(RC_ROOT, ".serve", "packs-cache");
export const PACKS_OUT = path.join(DIST, "packs");

/** The only entry point a generated pack extension needs. */
const EXTENSION_STUB = `/*---------------------------------------------------------------------------------------------
 *  Generated by scripts/packs.mjs. This extension exists so the workbench can
 *  load the pack as a built-in and the host's catalog scan can find it.
 *  The runtime itself lives in ./assets/ and runs in ./session.js, which this
 *  build does not ship yet (RUNTIMES.md milestone M3). The host reports the
 *  session as not implemented until it does.
 *--------------------------------------------------------------------------------------------*/
// @ts-check
"use strict";
function activate() {}
function deactivate() {}
module.exports = { activate, deactivate };
`;

/** The worker every pack points at, until an engine's createSession is real. */
const SESSION_STUB = `/* Generated by scripts/packs.mjs. The engine's worker entry.
 * Not implemented yet: RUNTIMES.md milestone M3 fills this in per engine. */
`;

// ---------------------------------------------------------------------------
// Cache
// ---------------------------------------------------------------------------

/**
 * Bytes for an expected sha256, from the cache or the network. The cache is
 * keyed by the digest, so a cached file is trusted by construction; verification
 * happens where the digest is known, which is everywhere this helper is used.
 *
 * @param {string} url
 * @param {string} sha256
 * @param {typeof fetch} [fetchImpl]
 * @param {string} [cacheDir]
 * @returns {Promise<Buffer>}
 */
export async function assetBytes(url, sha256, fetchImpl = fetch, cacheDir = CACHE_DIR) {
  const cached = path.join(cacheDir, sha256);
  if (existsSync(cached)) {
    return readFileSync(cached);
  }
  const response = await fetchImpl(url);
  if (!response.ok) {
    throw new Error(`Could not download ${url} (${response.status} ${response.statusText}).`);
  }
  const body = Buffer.from(await response.arrayBuffer());
  const digest = sha256Hex(body);
  if (digest !== sha256) {
    throw new Error(`Checksum mismatch for ${url}: expected ${sha256}, got ${digest}.`);
  }
  mkdirSync(cacheDir, { recursive: true });
  writeFileSync(cached, body);
  return body;
}

/** All pack ids defined under packs/, sorted. */
export function listPackIds(root = PACKS_SRC) {
  if (!existsSync(root)) {
    return [];
  }
  return readdirSync(root)
    .filter((entry) => {
      try {
        return existsSync(path.join(root, entry, "pack.json"));
      } catch {
        return false;
      }
    })
    .sort();
}

// ---------------------------------------------------------------------------
// Pin
// ---------------------------------------------------------------------------

/**
 * Fetch every asset of one pack and record its sha256 and bytes back into
 * packs/<id>/pack.json, preserving the other fields. Returns the updated pack.
 *
 * @param {string} id
 * @param {typeof fetch} [fetchImpl]
 * @param {string} [root]
 * @returns {Promise<any>}
 */
export async function pinPack(id, fetchImpl = fetch, root = PACKS_SRC) {
  const file = path.join(root, id, "pack.json");
  const pack = readPackDefinition(id, root);
  for (const asset of pack.assets) {
    const body = await fetchRaw(asset.url, fetchImpl);
    asset.bytes = body.length;
    asset.sha256 = sha256Hex(body);
    mkdirSync(CACHE_DIR, { recursive: true });
    writeFileSync(path.join(CACHE_DIR, asset.sha256), body);
  }
  writeFileSync(file, `${JSON.stringify(pack, null, 2)}\n`);
  return pack;
}

/**
 * Download bytes without a known digest yet (used only by --pin).
 *
 * @param {string} url
 * @param {typeof fetch} fetchImpl
 * @returns {Promise<Buffer>}
 */
async function fetchRaw(url, fetchImpl) {
  const response = await fetchImpl(url);
  if (!response.ok) {
    throw new Error(`Could not download ${url} (${response.status} ${response.statusText}).`);
  }
  return Buffer.from(await response.arrayBuffer());
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

/**
 * Build one pack into outDir/<id>/. Refuses to emit an unpinned pack, and
 * refuses a digest mismatch. Returns the built pack.
 *
 * @param {any} pack
 * @param {object} [options]
 * @param {typeof fetch} [options.fetchImpl]
 * @param {string} [options.outDir]
 * @param {string} [options.cacheDir]
 * @param {boolean} [options.offline]
 * @returns {Promise<any>}
 */
export async function buildPack(pack, options = {}) {
  const { fetchImpl = fetch, outDir = PACKS_OUT, cacheDir = CACHE_DIR, offline = false } = options;
  if (!isPinned(pack)) {
    throw new Error(
      `[${pack.id}] is not pinned. Run:  node scripts/packs.mjs --pin ${pack.id}`,
    );
  }
  const dest = path.join(outDir, pack.id);
  rmSync(dest, { recursive: true, force: true });
  mkdirSync(path.join(dest, "assets"), { recursive: true });

  // The license: an unmodified upstream runtime must keep its terms visible.
  // The pack author vendors the upstream LICENSE file at packs/<id>/LICENSE.
  // This is a hard requirement, like the extension gate: a runtime whose terms
  // are implied rather than shipped is a compliance problem that surfaces after
  // distribution, when it is expensive. (The license field in pack.json states
  // the SPDX id; the LICENSE file is the actual terms.)
  const license = path.join(PACKS_SRC, pack.id, "LICENSE");
  if (!existsSync(license)) {
    throw new Error(
      `[${pack.id}] has no packs/${pack.id}/LICENSE. Vendor the upstream license file before building.`,
    );
  }
  writeFileSync(path.join(dest, "LICENSE"), readFileSync(license));

  const locked = path.join(dest, ".writing");
  writeFileSync(locked, "interrupted build\n");

  for (const asset of pack.assets) {
    if (offline && !existsSync(path.join(cacheDir, asset.sha256))) {
      throw new Error(
        `[${pack.id}] asset "${asset.name}" is not in the cache (${asset.sha256}). Run without --offline once.`,
      );
    }
    const body = await assetBytes(asset.url, asset.sha256, fetchImpl, cacheDir);
    writeFileSync(path.join(dest, "assets", asset.name), body);
  }

  // The pack is an extension, so it gets an extension manifest plus a stub
  // entry, and the manifest the host probes. The LICENSE was written above.
  writeFileSync(path.join(dest, "package.json"), `${JSON.stringify(packPackageJson(pack), null, 2)}\n`);
  writeFileSync(path.join(dest, "extension.js"), EXTENSION_STUB);
  writeFileSync(path.join(dest, "session.js"), SESSION_STUB);
  writeFileSync(path.join(dest, "pack.json"), `${JSON.stringify(packManifest(pack), null, 2)}\n`);

  rmSync(locked, { force: true });
  console.log(
    `[packs] built ${pack.id} ${pack.version} (${installBytesFor(pack)} bytes)`,
  );
  return pack;
}

/**
 * Build every pinned pack and write dist/packs/catalog.json. Packs that are not
 * pinned are reported and skipped, never emitted.
 *
 * @param {object} [options]
 * @param {string[]} [options.only] build only these ids
 * @param {string} [options.root]
 * @param {string} [options.outDir]
 * @param {boolean} [options.offline]
 * @param {typeof fetch} [options.fetchImpl]
 * @returns {Promise<{ built: string[], skipped: string[] }>}
 */
export async function buildAll(options = {}) {
  const { only, root = PACKS_SRC, outDir = PACKS_OUT, offline = false, fetchImpl = fetch } = options;
  const ids = only && only.length > 0 ? only : listPackIds(root);
  const built = [];
  const skipped = [];

  for (const id of ids) {
    let pack;
    try {
      pack = readPackDefinition(id, root);
    } catch (error) {
      throw new Error(error.message);
    }
    if (!isPinned(pack)) {
      skipped.push(id);
      console.warn(`[packs] SKIP ${id}: not pinned (run --pin ${id})`);
      continue;
    }
    await buildPack(pack, { outDir, offline, fetchImpl });
    built.push(id);
  }

  const catalog = [];
  for (const id of built) {
    catalog.push(catalogEntry(readPackDefinition(id, root)));
  }
  mkdirSync(outDir, { recursive: true });
  writeFileSync(
    path.join(outDir, "catalog.json"),
    `${JSON.stringify(catalog, null, 2)}\n`,
  );
  console.log(`[packs] catalog: ${catalog.length} pack(s) at ${path.join(outDir, "catalog.json")}`);
  return { built, skipped };
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);

async function main() {
  if (args.includes("--list") || args.length === 0) {
    const ids = listPackIds();
    if (ids.length === 0) {
      console.log("[packs] no packs defined");
      return;
    }
    for (const id of ids) {
      const pack = readPackDefinition(id);
      const state = isPinned(pack)
        ? `pinned (${installBytesFor(pack)} bytes)`
        : "NOT pinned";
      console.log(`  ${id.padEnd(28)} ${pack.version.padEnd(10)} ${state}`);
    }
    return;
  }

  if (args.includes("--pin")) {
    const targets = args.filter((a) => !a.startsWith("--"));
    if (targets.length === 0) {
      console.error("usage: node scripts/packs.mjs --pin <id>...");
      process.exit(1);
    }
    for (const id of targets) {
      const pack = await pinPack(id);
      console.log(`[packs] pinned ${id} ${pack.version}`);
    }
    return;
  }

  if (args.includes("--build")) {
    const onlyIndex = args.indexOf("--id");
    const only = onlyIndex !== -1 ? args.slice(onlyIndex + 1).filter((a) => !a.startsWith("--")) : undefined;
    const offline = args.includes("--offline");
    await buildAll({ only, offline });
    return;
  }

  console.error(
    "usage: node scripts/packs.mjs --list | --pin <id>... | --build [--id <id>] [--offline]",
  );
  process.exit(1);
}

// Only run the CLI when executed directly, so serve.mjs and check-deploy.mjs can
// import the exports (PACKS_OUT, buildAll, ...) without side effects.
const isMain = process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href;
if (isMain) {
  main().catch((error) => {
    console.error(`[packs] ${error.message}`);
    process.exit(1);
  });
}